name: Deploy Jupyter Book with GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install jupyter-book sphinx_inline_tabs

      - name: Build Jupyter Book
        run: |
          jupyter-book build .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_build/html'  # Ensure the path points to your built HTML directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
